---
- hosts: '*'
  gather_facts: no
  connection: network_cli

  tasks:

  - name: GATHER FACTS
    ios_facts:

  - copy: content="{{ iosfacts_out | to_nice_json }}" dest="out/{{inventory_hostname}}_iosfacts.json"